import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home({data}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to my app!</h1>
        <div id="secrets">
          <h1>Environment variables in the container</h1>
          <pre>{JSON.stringify(data)}</pre>
        </div>
      </main>

      <footer className={styles.footer}>Sample app</footer>
    </div>
  );
}

export async function getServerSideProps() {
  const data = process.env;
  return {props: {data}};
}
